//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cpanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        public string id { get; set; }
        public string book_title { get; set; }
        public string author { get; set; }
        public string publisher { get; set; }
        public int stock { get; set; }
        public int price { get; set; }
        public string id_user { get; set; }
    
        public virtual users users { get; set; }
    }
}
